import type { SourcePreset, SourcePresetGroup } from "./types";

export const verifiedFreeSourcePresets: SourcePreset[] = [
  {
    id: "hugging-face-blog",
    name: "Hugging Face Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 120,
    coverage: "模型、数据集、开源 AI 工具和生态更新",
    tags: ["ai", "models", "open-source"],
    entities: ["Hugging Face"],
    quality: "high"
  },
  {
    id: "ollama-blog",
    name: "Ollama Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://ollama.com/blog/rss.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "本地模型运行时和工具更新",
    tags: ["ai", "local-models"],
    entities: ["Ollama"],
    quality: "high"
  },
  {
    id: "aws-machine-learning-blog",
    name: "AWS Machine Learning Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "AWS 官方 AI/ML 工程实践",
    tags: ["ai", "cloud", "mlops"],
    entities: ["AWS"],
    quality: "high"
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://blog.google/technology/ai/rss/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Google 官方 AI 新闻和产品研究动态",
    tags: ["ai", "official"],
    entities: ["Google"],
    quality: "high"
  },
  {
    id: "github-changelog",
    name: "GitHub Changelog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://github.blog/changelog/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 60,
    coverage: "GitHub 官方产品更新和平台变更",
    tags: ["changelog", "developer-tooling"],
    entities: ["GitHub"],
    quality: "high"
  },
  {
    id: "github-engineering",
    name: "GitHub Engineering",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://github.blog/engineering/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "GitHub 官方工程文章",
    tags: ["engineering", "developer-tooling"],
    entities: ["GitHub"],
    quality: "high"
  },
  {
    id: "vercel-changelog",
    name: "Vercel Changelog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://vercel.com/changelog/rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 60,
    coverage: "Vercel 官方产品更新和平台变更",
    tags: ["changelog", "frontend", "cloud"],
    entities: ["Vercel"],
    quality: "high"
  },
  {
    id: "nextjs-blog",
    name: "Next.js Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://nextjs.org/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Next.js 官方框架动态",
    tags: ["frontend", "framework"],
    entities: ["Next.js", "Vercel"],
    quality: "high"
  },
  {
    id: "react-blog",
    name: "React Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://react.dev/rss.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "React 官方框架动态",
    tags: ["frontend", "framework"],
    entities: ["React"],
    quality: "high"
  },
  {
    id: "nodejs-blog",
    name: "Node.js Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://nodejs.org/en/feed/blog.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Node.js 官方博客",
    tags: ["runtime", "javascript"],
    entities: ["Node.js"],
    quality: "high"
  },
  {
    id: "nodejs-releases",
    name: "Node.js Releases",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://nodejs.org/en/feed/releases.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 120,
    coverage: "Node.js 官方版本发布",
    tags: ["runtime", "release"],
    entities: ["Node.js"],
    quality: "high"
  },
  {
    id: "typescript-blog",
    name: "TypeScript Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://devblogs.microsoft.com/typescript/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "TypeScript 官方语言动态",
    tags: ["typescript", "language"],
    entities: ["TypeScript", "Microsoft"],
    quality: "high"
  },
  {
    id: "tailwind-css-blog",
    name: "Tailwind CSS Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://tailwindcss.com/feeds/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Tailwind CSS 官方框架动态",
    tags: ["frontend", "css"],
    entities: ["Tailwind CSS"],
    quality: "high"
  },
  {
    id: "deno-blog",
    name: "Deno Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://deno.com/feed",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Deno 官方运行时动态",
    tags: ["runtime", "javascript"],
    entities: ["Deno"],
    quality: "high"
  },
  {
    id: "bun-blog",
    name: "Bun Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://bun.sh/rss.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Bun 官方运行时动态",
    tags: ["runtime", "javascript"],
    entities: ["Bun"],
    quality: "high"
  },
  {
    id: "rust-blog",
    name: "Rust Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://blog.rust-lang.org/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Rust 官方语言动态",
    tags: ["language", "systems"],
    entities: ["Rust"],
    quality: "high"
  },
  {
    id: "go-blog",
    name: "Go Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://go.dev/blog/feed.atom",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Go 官方语言动态",
    tags: ["language", "backend"],
    entities: ["Go"],
    quality: "high"
  },
  {
    id: "kubernetes-blog",
    name: "Kubernetes Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://kubernetes.io/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Kubernetes 官方云原生动态",
    tags: ["cloud-native", "infrastructure"],
    entities: ["Kubernetes"],
    quality: "high"
  },
  {
    id: "docker-blog",
    name: "Docker Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://www.docker.com/blog/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Docker 官方容器和开发者工具动态",
    tags: ["infrastructure", "containers"],
    entities: ["Docker"],
    quality: "high"
  },
  {
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://blog.cloudflare.com/rss/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Cloudflare 官方网络、平台和安全动态",
    tags: ["infrastructure", "security"],
    entities: ["Cloudflare"],
    quality: "high"
  },
  {
    id: "mozilla-hacks",
    name: "Mozilla Hacks",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://hacks.mozilla.org/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Web 平台工程文章",
    tags: ["web", "browser"],
    entities: ["Mozilla"],
    quality: "high"
  },
  {
    id: "web-dev",
    name: "web.dev",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://web.dev/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Google Web 平台工程文章",
    tags: ["web", "browser"],
    entities: ["Google", "web.dev"],
    quality: "high"
  },
  {
    id: "chrome-developers-blog",
    name: "Chrome Developers Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://developer.chrome.com/blog/feed.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Chrome 官方浏览器平台动态",
    tags: ["web", "browser"],
    entities: ["Chrome", "Google"],
    quality: "high"
  },
  {
    id: "android-developers-blog",
    name: "Android Developers Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://android-developers.googleblog.com/feeds/posts/default?alt=rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Android 官方开发者动态",
    tags: ["android", "mobile"],
    entities: ["Android", "Google"],
    quality: "high"
  },
  {
    id: "chromium-blog",
    name: "Chromium Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://blog.chromium.org/feeds/posts/default?alt=rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Chromium 官方浏览器平台动态",
    tags: ["web", "browser"],
    entities: ["Chromium", "Google"],
    quality: "high"
  },
  {
    id: "apple-developer-news",
    name: "Apple Developer News",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://developer.apple.com/news/rss/news.rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Apple 官方开发者动态",
    tags: ["apple", "mobile"],
    entities: ["Apple"],
    quality: "high"
  },
  {
    id: "stripe-blog",
    name: "Stripe Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://stripe.com/blog/feed.rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 240,
    coverage: "Stripe 产品和平台工程动态",
    tags: ["payments", "platform"],
    entities: ["Stripe"],
    quality: "high"
  },
  {
    id: "cisa-advisories",
    name: "CISA Advisories",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 120,
    coverage: "CISA 官方安全公告",
    tags: ["security", "advisory"],
    entities: ["CISA"],
    quality: "high"
  },
  {
    id: "google-security-blog",
    name: "Google Security Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://security.googleblog.com/feeds/posts/default?alt=rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "Google 官方安全博客",
    tags: ["security"],
    entities: ["Google"],
    quality: "high"
  },
  {
    id: "github-security-blog",
    name: "GitHub Security Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://github.blog/security/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "GitHub 官方安全文章",
    tags: ["security", "developer-tooling"],
    entities: ["GitHub"],
    quality: "high"
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI&start=0&max_results=25&sortBy=submittedDate&sortOrder=descending",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "人工智能论文",
    tags: ["research", "ai"],
    entities: ["arXiv"],
    quality: "high"
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.CL&start=0&max_results=25&sortBy=submittedDate&sortOrder=descending",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "NLP 和计算语言学论文",
    tags: ["research", "nlp"],
    entities: ["arXiv"],
    quality: "high"
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.LG&start=0&max_results=25&sortBy=submittedDate&sortOrder=descending",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "机器学习论文",
    tags: ["research", "machine-learning"],
    entities: ["arXiv"],
    quality: "high"
  },
  {
    id: "arxiv-cs-se",
    name: "arXiv cs.SE",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.SE&start=0&max_results=25&sortBy=submittedDate&sortOrder=descending",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "软件工程论文",
    tags: ["research", "software-engineering"],
    entities: ["arXiv"],
    quality: "high"
  },
  {
    id: "arxiv-stat-ml",
    name: "arXiv stat.ML",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "atom",
    url: "https://export.arxiv.org/api/query?search_query=cat:stat.ML&start=0&max_results=25&sortBy=submittedDate&sortOrder=descending",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "统计机器学习论文",
    tags: ["research", "machine-learning"],
    entities: ["arXiv"],
    quality: "high"
  },
  {
    id: "hacker-news-rss",
    name: "Hacker News RSS",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://news.ycombinator.com/rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 30,
    coverage: "开发者社区高信号讨论",
    tags: ["community", "developer"],
    entities: ["Hacker News"],
    quality: "high"
  },
  {
    id: "lobsters-rss",
    name: "Lobsters RSS",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://lobste.rs/rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 45,
    coverage: "开发者社区高信号讨论",
    tags: ["community", "developer"],
    entities: ["Lobsters"],
    quality: "high"
  },
  {
    id: "ruanyifeng-weekly",
    name: "阮一峰周刊",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://feeds.feedburner.com/ruanyifeng",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "中文技术周刊和趋势观察",
    tags: ["zh", "weekly"],
    entities: ["阮一峰"],
    quality: "high"
  },
  {
    id: "sspai",
    name: "少数派",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://sspai.com/feed",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 180,
    coverage: "中文科技、效率和产品内容",
    tags: ["zh", "productivity"],
    entities: ["少数派"],
    quality: "high"
  },
  {
    id: "infoq-cn",
    name: "InfoQ 中文",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://www.infoq.cn/feed",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 120,
    coverage: "中文工程、架构和技术管理内容",
    tags: ["zh", "architecture"],
    entities: ["InfoQ"],
    quality: "high"
  },
  {
    id: "meituan-tech",
    name: "美团技术团队",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://tech.meituan.com/feed/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "中文工程实践文章",
    tags: ["zh", "engineering"],
    entities: ["美团"],
    quality: "high"
  },
  {
    id: "pingcap-blog",
    name: "PingCAP Blog",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://www.pingcap.com/blog/rss/",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 720,
    coverage: "数据库和基础设施工程文章",
    tags: ["database", "infrastructure"],
    entities: ["PingCAP", "TiDB"],
    quality: "high"
  },
  {
    id: "solidot",
    name: "Solidot",
    group: "default",
    adapter: "feed",
    access: "feed",
    format: "rss",
    url: "https://www.solidot.org/index.rss",
    free: true,
    verified: true,
    priority: "M1",
    refreshIntervalMinutes: 120,
    coverage: "中文科技新闻",
    tags: ["zh", "tech-news"],
    entities: ["Solidot"],
    quality: "high"
  },
  ...releasePresets(),
  ...apiPresets(),
  ...optionalPresets()
];

export function getDefaultSourcePresets(): SourcePreset[] {
  const priorityById = new Map([
    "hacker-news-rss",
    "lobsters-rss",
    "hugging-face-blog",
    "google-ai-blog",
    "aws-machine-learning-blog",
    "ollama-blog",
    "cloudflare-blog",
    "ruanyifeng-weekly",
    "infoq-cn",
    "meituan-tech",
    "solidot",
    "arxiv-cs-ai",
    "arxiv-cs-cl",
    "arxiv-cs-lg"
  ].map((id, index) => [id, index]));

  return verifiedFreeSourcePresets
    .filter((source) => source.group === "default" || source.group === "release" || source.group === "api")
    .sort((left, right) => {
      const leftPriority = priorityById.get(left.id) ?? Number.MAX_SAFE_INTEGER;
      const rightPriority = priorityById.get(right.id) ?? Number.MAX_SAFE_INTEGER;

      return leftPriority - rightPriority || left.name.localeCompare(right.name);
    });
}

export function getSourcePresetsByGroup(): Record<SourcePresetGroup, SourcePreset[]> {
  return {
    default: verifiedFreeSourcePresets.filter((source) => source.group === "default"),
    release: verifiedFreeSourcePresets.filter((source) => source.group === "release"),
    api: verifiedFreeSourcePresets.filter((source) => source.group === "api"),
    optional: verifiedFreeSourcePresets.filter((source) => source.group === "optional")
  };
}

function releasePresets(): SourcePreset[] {
  return [
    ["github-release-nextjs", "GitHub Release: Next.js", "https://github.com/vercel/next.js/releases.atom", ["Next.js", "Vercel"]],
    ["github-release-react", "GitHub Release: React", "https://github.com/facebook/react/releases.atom", ["React"]],
    ["github-release-nodejs", "GitHub Release: Node.js", "https://github.com/nodejs/node/releases.atom", ["Node.js"]],
    ["github-release-typescript", "GitHub Release: TypeScript", "https://github.com/microsoft/TypeScript/releases.atom", ["TypeScript", "Microsoft"]],
    ["github-release-pnpm", "GitHub Release: pnpm", "https://github.com/pnpm/pnpm/releases.atom", ["pnpm"]],
    ["github-release-vite", "GitHub Release: Vite", "https://github.com/vitejs/vite/releases.atom", ["Vite"]],
    ["github-release-vitest", "GitHub Release: Vitest", "https://github.com/vitest-dev/vitest/releases.atom", ["Vitest"]],
    ["github-release-tailwindcss", "GitHub Release: Tailwind CSS", "https://github.com/tailwindlabs/tailwindcss/releases.atom", ["Tailwind CSS"]],
    ["github-release-eslint", "GitHub Release: ESLint", "https://github.com/eslint/eslint/releases.atom", ["ESLint"]],
    ["github-release-playwright", "GitHub Release: Playwright", "https://github.com/microsoft/playwright/releases.atom", ["Playwright", "Microsoft"]],
    ["github-release-drizzle-orm", "GitHub Release: Drizzle ORM", "https://github.com/drizzle-team/drizzle-orm/releases.atom", ["Drizzle ORM"]],
    ["github-release-turborepo", "GitHub Release: Turborepo", "https://github.com/vercel/turborepo/releases.atom", ["Turborepo", "Vercel"]],
    ["github-release-bun", "GitHub Release: Bun", "https://github.com/oven-sh/bun/releases.atom", ["Bun"]],
    ["github-release-deno", "GitHub Release: Deno", "https://github.com/denoland/deno/releases.atom", ["Deno"]],
    ["github-release-supabase", "GitHub Release: Supabase", "https://github.com/supabase/supabase/releases.atom", ["Supabase"]],
    ["github-release-langchain-js", "GitHub Release: LangChain JS", "https://github.com/langchain-ai/langchainjs/releases.atom", ["LangChain"]],
    ["github-release-openai-node", "GitHub Release: OpenAI Node", "https://github.com/openai/openai-node/releases.atom", ["OpenAI"]],
    ["github-release-openai-python", "GitHub Release: OpenAI Python", "https://github.com/openai/openai-python/releases.atom", ["OpenAI"]],
    [
      "github-release-anthropic-sdk-ts",
      "GitHub Release: Anthropic SDK TS",
      "https://github.com/anthropics/anthropic-sdk-typescript/releases.atom",
      ["Anthropic"]
    ]
  ].map(([id, name, url, entities]) =>
    makePreset({
      id: id as string,
      name: name as string,
      group: "release",
      format: "atom",
      url: url as string,
      coverage: "GitHub release、版本说明和 breaking changes",
      tags: ["release", "github"],
      entities: entities as string[],
      refreshIntervalMinutes: 120
    })
  );
}

function apiPresets(): SourcePreset[] {
  return [
    ["hn-api-new-stories", "HN API New Stories", "https://hacker-news.firebaseio.com/v0/newstories.json", ["Hacker News"]],
    ["hn-api-top-stories", "HN API Top Stories", "https://hacker-news.firebaseio.com/v0/topstories.json", ["Hacker News"]],
    ["npm-registry-next", "npm Registry Next", "https://registry.npmjs.org/next", ["npm", "Next.js"]],
    ["npm-registry-react", "npm Registry React", "https://registry.npmjs.org/react", ["npm", "React"]],
    ["pypi-fastapi", "PyPI FastAPI", "https://pypi.org/pypi/fastapi/json", ["PyPI", "FastAPI"]],
    ["pypi-langchain", "PyPI LangChain", "https://pypi.org/pypi/langchain/json", ["PyPI", "LangChain"]]
  ].map(([id, name, url, entities]) =>
    makePreset({
      id: id as string,
      name: name as string,
      group: "api",
      adapter: "json-api",
      access: "api",
      format: "json",
      url: url as string,
      priority: "M2",
      coverage: "免费官方 JSON API，适合 M2 Public API Adapter",
      tags: ["api"],
      entities: entities as string[],
      refreshIntervalMinutes: 120
    })
  );
}

function optionalPresets(): SourcePreset[] {
  return [
    ["hnrss-frontpage", "HNRSS Frontpage", "https://hnrss.org/frontpage", "rss", ["Hacker News"]],
    ["krebs-on-security", "Krebs on Security", "https://krebsonsecurity.com/feed/", "rss", ["Krebs on Security"]],
    ["v2ex", "V2EX", "https://www.v2ex.com/index.xml", "atom", ["V2EX"]],
    ["oschina-news", "开源中国资讯", "https://www.oschina.net/news/rss", "rss", ["OSCHINA"]],
    ["devto-ai", "DEV.to AI Tag", "https://dev.to/feed/tag/ai", "rss", ["DEV.to"]],
    ["devto-javascript", "DEV.to JavaScript Tag", "https://dev.to/feed/tag/javascript", "rss", ["DEV.to"]]
  ].map(([id, name, url, format, entities]) =>
    makePreset({
      id: id as string,
      name: name as string,
      group: "optional",
      format: format as "rss" | "atom",
      url: url as string,
      priority: "optional",
      coverage: "可执行免费源，但默认不开启，需要更强过滤",
      tags: ["optional"],
      entities: entities as string[],
      refreshIntervalMinutes: 120,
      quality: "medium"
    })
  );
}

function makePreset(input: {
  id: string;
  name: string;
  group: SourcePresetGroup;
  format: "rss" | "atom" | "json";
  url: string;
  coverage: string;
  tags: string[];
  entities: string[];
  adapter?: "feed" | "json-api";
  access?: "feed" | "api";
  priority?: "M1" | "M2" | "optional";
  refreshIntervalMinutes?: number;
  quality?: "high" | "medium";
}): SourcePreset {
  return {
    adapter: input.adapter ?? "feed",
    access: input.access ?? "feed",
    free: true,
    verified: true,
    priority: input.priority ?? "M1",
    refreshIntervalMinutes: input.refreshIntervalMinutes ?? 120,
    quality: input.quality ?? "high",
    ...input
  };
}
